; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	C:\Users\Ben\Documents\Visual Studio 2012\Projects\CO2411Assignment\dll_Sort\dllmain.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	_DllMain@12
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
; Function compile flags: /Odtp /RTCsu /ZI
; File c:\users\ben\documents\visual studio 2012\projects\co2411assignment\dll_sort\dllmain.cpp
;	COMDAT _DllMain@12
_TEXT	SEGMENT
tv64 = -196						; size = 4
_hModule$ = 8						; size = 4
_ul_reason_for_call$ = 12				; size = 4
_lpReserved$ = 16					; size = 4
_DllMain@12 PROC					; COMDAT

; 8    : {

	push	ebp
	mov	ebp, esp
	sub	esp, 196				; 000000c4H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-196]
	mov	ecx, 49					; 00000031H
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 9    : 	switch (ul_reason_for_call)

	mov	eax, DWORD PTR _ul_reason_for_call$[ebp]
	mov	DWORD PTR tv64[ebp], eax

; 10   : 	{
; 11   : 	case DLL_PROCESS_ATTACH:
; 12   : 	case DLL_THREAD_ATTACH:
; 13   : 	case DLL_THREAD_DETACH:
; 14   : 	case DLL_PROCESS_DETACH:
; 15   : 		break;
; 16   : 	}
; 17   : 	return TRUE;

	mov	eax, 1

; 18   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	12					; 0000000cH
_DllMain@12 ENDP
_TEXT	ENDS
END
