; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	C:\Users\Ben\Documents\Visual Studio 2012\Projects\CO2411Assignment\dll_Sort\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UfhvihUyvmUwlxfnvmghUerhfzoLhgfwrlLCABCUkilqvxghUxlCEBBzhhrtmnvmgUwooPhligUwvyftUhgwzucOlyq@1C56544E5809D074
;	COMDAT ___@@_PchSym_@00@UfhvihUyvmUwlxfnvmghUerhfzoLhgfwrlLCABCUkilqvxghUxlCEBBzhhrtmnvmgUwooPhligUwvyftUhgwzucOlyq@1C56544E5809D074
_BSS	SEGMENT
___@@_PchSym_@00@UfhvihUyvmUwlxfnvmghUerhfzoLhgfwrlLCABCUkilqvxghUxlCEBBzhhrtmnvmgUwooPhligUwvyftUhgwzucOlyq@1C56544E5809D074 DD 01H DUP (?)
_BSS	ENDS
END
