; Listing generated by Microsoft (R) Optimizing Compiler Version 17.00.61219.0 

	TITLE	C:\Users\Ben\Documents\Visual Studio 2012\Projects\CO2411Assignment\dll_Sort\dllmain.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

EXTRN	@__security_check_cookie@4:PROC
PUBLIC	_DllMain@12
EXTRN	___CxxFrameHandler3:PROC
EXTRN	___security_cookie:DWORD
; Function compile flags: /Ogtp
; File c:\users\ben\documents\visual studio 2012\projects\co2411assignment\dll_sort\dllmain.cpp
;	COMDAT _DllMain@12
_TEXT	SEGMENT
_hModule$ = 8						; size = 4
_ul_reason_for_call$ = 12				; size = 4
_lpReserved$ = 16					; size = 4
_DllMain@12 PROC					; COMDAT

; 9    : 	switch (ul_reason_for_call)
; 10   : 	{
; 11   : 	case DLL_PROCESS_ATTACH:
; 12   : 	case DLL_THREAD_ATTACH:
; 13   : 	case DLL_THREAD_DETACH:
; 14   : 	case DLL_PROCESS_DETACH:
; 15   : 		break;
; 16   : 	}
; 17   : 	return TRUE;

	mov	eax, 1

; 18   : }

	ret	12					; 0000000cH
_DllMain@12 ENDP
_TEXT	ENDS
END
